from typing import Protocol
from app.identity import Actor
from app.schemas import RefundInput, ShipmentInput, ReturnInput


class OrderCommands(Protocol):
    def get(self, actor: Actor, order_id: str, admin: bool = False) -> dict: ...
    def refund(self, actor: Actor, order_id: str, command: RefundInput) -> dict: ...
    def ship(self, actor: Actor, order_id: str, command: ShipmentInput) -> dict: ...
    def list(self, actor: Actor, admin: bool = False) -> list[dict]: ...
    def dashboard(self, actor: Actor) -> dict: ...
    def deliver(self, actor: Actor, order_id: str) -> dict: ...
    def request_return(self, actor: Actor, order_id: str, command: ReturnInput) -> dict: ...
    def receive_return(self, actor: Actor, return_id: str, sellable: bool) -> dict: ...
