from typing import Protocol
from app.identity import Actor
from app.schemas import CampaignInput


class ContentCommands(Protocol):
    def campaign(self, department: str) -> dict: ...
    def save(self, actor: Actor, department: str, command: CampaignInput) -> dict: ...
    def history(self, actor: Actor, department: str) -> list[dict]: ...
    def publish(self, actor: Actor, revision_id: str) -> dict: ...
