from typing import Protocol
from app.identity import Actor
from app.schemas import SupportInput


class Operations(Protocol):
    def submit_support(self, actor: Actor, command: SupportInput) -> dict: ...
    def support_list(self, actor: Actor) -> list[dict]: ...
    def image(self, actor: Actor, raw: bytes) -> dict: ...
    def pause(self, actor: Actor, paused: bool) -> dict: ...
    def video(self, actor: Actor, raw: bytes) -> dict: ...
    def job(self, actor: Actor, key: str) -> dict: ...
    def retry(self, actor: Actor, job_id: str) -> dict: ...
