from typing import Protocol
from app.identity import Actor
from app.schemas import ProductInput, ProductPage, Product, StockAdjustment


class Catalog(Protocol):
    def list(self, **filters) -> ProductPage: ...
    def get(self, slug: str, actor: Actor | None = None) -> Product: ...
    def save(self, actor: Actor, command: ProductInput, product_id: str | None = None) -> Product: ...
    def publish(self, actor: Actor, product_id: str, version: int, status: str = "published") -> Product: ...
    def stock(self, actor: Actor, command: StockAdjustment) -> dict: ...
