from typing import Protocol
from app.identity import Actor
from app.schemas import CartMutation, Address, Checkout


class CheckoutCommands(Protocol):
    def cart(self, actor: Actor) -> dict: ...
    def mutate(self, actor: Actor, command: CartMutation) -> dict: ...
    def quote(self, actor: Actor, address: Address) -> dict: ...
    def reserve(self, actor: Actor, command: Checkout) -> dict: ...
    def saved(self, actor: Actor) -> list: ...
    def save(self, actor: Actor, product_id: str, remove: bool = False) -> dict: ...
