from typing import Protocol


class PaymentGateway(Protocol):
    def create_order(self, order: dict) -> dict: ...
    def fetch_payment(self, payment_id: str) -> dict: ...
    def fetch_order_payments(self, provider_id: str) -> dict: ...
    def refund(self, payment_id: str, amount: int, refund_id: str) -> dict: ...
    def verify(self, raw: bytes, signature: str) -> None: ...
    def find_order(self, order: dict) -> dict | None: ...
    def find_refund(self, payment_id: str, refund_id: str) -> dict | None: ...
